export const news = [
    {
      id: '12',
      title: 'Simple news 1',
      description: 'This is about muffin Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ',
      date: 1606125923036,
      approved: true,
    },
    {
      id: '122',
      title: 'Hard news 2',
      description: 'This is about hard Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ',
      date: 1602225963036,
      approved: true,
    },
    {
      id: '13321',
      title: 'New Title 3',
      description: 'This is about sport Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ',
      date: 1606425963036,
      approved: true,
    },
    {
      id: 'd3sfe',
      title: 'New Title 3',
      description: 'This is about sport Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ',
      date: 1606425963316,
      approved: true,
    },
    {
      id: 'c3234',
      title: 'New Title 3',
      description: 'This is about sport Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ',
      date: 160325963036,
      approved: true,
    },
    {
      id: '211312',
      title: 'From Future',
      description: 'EveryThing is Ok!',
      date: 162333325963036,
      approved: true,
    },
    {
      id: '133222',
      title: 'The Best News!',
      description: 'One day, a good King and his beautiful Queen have a baby. They are very happy. "Let’s have a party," says the King. The King and Queen invite their friends to the party. They also invite seven good fairies. Today is the party! Everybody gives a present to the baby princess. The fairies also give presents. Their presents are very special. "You will be beautiful," says the first fairy. "You will be clever," says the second fairy. "You will be kind," says the third fairy. "You will sing," says the fourth fairy. "You will dance," says the fifth fairy. "You will always be happy," says the sixth fairy. Suddenly, somebody knocks on the palace door',
      date: 1606485963036,
      approved: false,
    },
];
